services:
  trackmania:
    build: ./trackmania
    restart: always
    environment: &tmenv
      TM_MASTERSERVER_LOGIN: ${TM_MASTERSERVER_LOGIN}
      TM_MASTERSERVER_PASSWORD: ${TM_MASTERSERVER_PASSWORD}
      TM_SERVER_NAME: Match Server
      TM_SERVER_MAX_PLAYERS: ${TM_SERVER_MAX_PLAYERS:-32}
      TM_SERVER_PASSWORD: ${TM_SERVER_PASSWORD}
      TM_GAME_SETTINGS: maplist.txt
      TM_SYSTEM_XMLRPC_ALLOWREMOTE: "true"
      TM_SYSTEM_FORCE_IP_ADDRESS: "${TM_SYSTEM_FORCE_IP_ADDRESS}:2350"
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
    expose:
      - "5000"
    volumes:
      - userdata:/server/UserData
  maniacontrol:
    build: ./maniacontrol
    restart: always
    environment:
      TM_SERVER_NAME: trackmania
      MANIACONTROL_DB_HOST: ${MANIACONTROL_DB_HOST}
      MANIACONTROL_DB_NAME: ${MANIACONTROL_DB_NAME:-maniacontrol}
      MANIACONTROL_DB_USER: ${MANIACONTROL_DB_USER:-maniacontrol}
      MANIACONTROL_DB_PASSWORD: ${MANIACONTROL_DB_PASSWORD}
      MANIACONTROL_ADMINS: ${MANIACONTROL_ADMINS}
    volumes:
      - userdata:/server/UserData
    depends_on:
      - trackmania

volumes:
  userdata: {}
